TEAM_HOME = "france"
TEAM_HOME_ABBREVIATION = "fra"
TEAM_AWAY = "croatia"
TEAM_AWAY_ABBREVIATION = "cro"
KEYWORDS_LIST = [
    TEAM_HOME,
    TEAM_HOME_ABBREVIATION,
    TEAM_AWAY,
    TEAM_AWAY_ABBREVIATION
]
LANGUAGES_LIST = ["en"]
FETCHED_TWEETS_FILE = "tweets.csv"
FIELDNAMES = ['time', 'text']
